name           = "App-xlate"
badges         = [ "github-actions/test.yml", "metacpan" ]
module_maker   = "ModuleBuildTiny"
static_install = "auto"
script_files   = [ "script/xlate" ]

[release]
branch = "main"

[FileGatherer]
exclude_match = [ '^images/.*' ]
